// Generated by ReScript, PLEASE EDIT WITH CARE

import * as CssJs from "../node_modules/bs-css-emotion/src/CssJs.bs.js";
import * as React from "react";
import * as Caml_option from "../node_modules/rescript/lib/es6/caml_option.js";

var deleteProp = ((newProps, key) => delete newProps[key]);

function getOrEmpty(str) {
  if (str !== undefined) {
    return " " + str;
  } else {
    return "";
  }
}

function styles(colorOpt, param) {
  var color = colorOpt !== undefined ? colorOpt : CssJs.hex("4299E1");
  return CssJs.style([
              CssJs.label("Link"),
              CssJs.fontSize({
                    NAME: "rem",
                    VAL: 1.875
                  }),
              CssJs.lineHeight({
                    NAME: "abs",
                    VAL: 1.5
                  }),
              CssJs.textDecoration("none"),
              CssJs.margin({
                    NAME: "pxFloat",
                    VAL: 0
                  }),
              CssJs.padding2({
                    NAME: "pxFloat",
                    VAL: 10
                  }, {
                    NAME: "pxFloat",
                    VAL: 0
                  }),
              CssJs.color(color)
            ]);
}

function make(props) {
  var className = styles(Caml_option.undefined_to_opt(props.color), undefined) + getOrEmpty(Caml_option.undefined_to_opt(props.className));
  var stylesObject = {
    className: className,
    ref: Caml_option.undefined_to_opt(props.innerRef)
  };
  var newProps = Object.assign({}, props, stylesObject);
  deleteProp(newProps, "color");
  deleteProp(newProps, "innerRef");
  return React.createElement("a", newProps);
}

var Link = {
  deleteProp: deleteProp,
  getOrEmpty: getOrEmpty,
  styles: styles,
  make: make
};

function App$Button(Props) {
  var count = Props.count;
  var times = count !== 1 ? (
      count !== 2 ? String(count) + " times" : "twice"
    ) : "once";
  var msg = "Click me " + times;
  return React.createElement("button", undefined, msg);
}

var Button = {
  make: App$Button
};

export {
  Link ,
  Button ,
}
/* CssJs Not a pure module */
